name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: yezz123/setup-uv@v4
      - run: uv --version
      - name: Install cookiecutter tool
        run: |
          uv pip install install cookiecutter
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Create plugin
        run: |
          cookiecutter . --no-input
      - name: Create environment and install dependencies
        run: |
          uv pip install -U polars maturin mypy pytest pip
          make install
        working-directory: my_plugin
      - name: Run linting and tests
        run: |
          mypy my_plugin tests
          pytest
        working-directory: my_plugin
      - name: Check version
        run: |
          python -c 'import my_plugin; print(my_plugin.__version__)'
        working-directory: my_plugin
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: yezz123/setup-uv@v4
      - run: uv --version
      - name: Install cookiecutter tool
        run: |
          uv pip install install cookiecutter
      - name: Create plugin
        run: |
          cookiecutter . --no-input
      - name: Create environment and install dependencies
        run: |
          uv pip install -U polars maturin mypy pytest pip
          make install
        working-directory: my_plugin
      - name: Run linting and tests
        run: |
          mypy my_plugin tests
          pytest
        working-directory: my_plugin
      - name: Check version
        run: |
          python -c 'import my_plugin; print(my_plugin.__version__)'
        working-directory: my_plugin
